spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crew_db?serverTimezone=UTC
    username : developer
    password : password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: trued
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9b4ce362573aae294aade4441c8af74b
            client-secret: ljYMqsCGAXDFBAzJjSGyK1cxsgXfVNLh
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/callback/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri:  https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt :
  secret : D3JfVb1FbPpOZgqugaaThvp1Kc4OyRP9nDXUjavPO1E=

